name: Keep Server Alive

on:
  schedule:
    - cron: '*/60 * * * *'  # Run every 60 minutes
  workflow_dispatch:        # Can run workflow manually

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Send Ping Request to Server
        env:
          SERVER_URL: "https://christian-penthatius.com/"
        run: |
          curl -X GET $SERVER_URL || echo "Ping failed"
